package hb;
// Generated Sep 30, 2012 8:35:41 AM by Hibernate Tools 3.2.1.GA

import java.util.Set;




/**
 * UserTable generated by hbm2java
 */
public class UserTable  implements java.io.Serializable {


     private int userid;
     private String firstname;
     private Set phones;
     
   
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public void setPhones(Set phones)
    {
        this.phones=phones;
    }
    public Set getPhones()
    {
        return phones;
    }
}


